### ISSUE TITLE
SEARCH_LIMIT in elastic.py is not configurable

### ISSUE THREAD

**Issue by zdenekpizl** [m110/grafcli#23]
Hi,

 https://github.com/m110/grafcli/blob/51e535dc67ac5bd59c307505f0a58d3526c9b6a1/grafcli/storage/elastic.py#L13 - if you have got more than 100 dashboards (100 is hardcoded default) you cannot get them apparently

Could it be configurable? Thank you, .zp.

**Comment by m110** [comment]
I'm dropping backends other than API in the new release, so will just close this one.
